### ISSUE TITLE
El plugin no funciona con Chrome

### ISSUE THREAD

**Issue by Corobori** [TransbankDevelopers/transbank-plugin-opencart-webpay#25]
**Describe el bug**

Pago por el plugin utilizando Chrome arrojan un error "Error en el pago, carro inválido".

**Para reproducir**

1. CON Chrome Ir a https://corobori.tienda/joyas/
2. Comprar un producto
3. Proceder con el pago. 

**Comportamiento observado**

A la vuelta el sistema arroja un error "Error en el pago, carro inválido" y el orden se encuentra en OpenCart "Missing orders"

**Comportamiento esperado**

Pasar al recibo del pago

**Capturas de pantalla**

Ver ejemplos: https://www.screencast.com/t/0X9x8sifz

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: 2.2.0
- Opencart:  3.0.3.6
- PHP: 7.3.21 (Opencart no corre con un PHP inferior) Yo se que su sistema dice Error!: Version no soportada pero OpenCart requiere 7.3 por lo tanto tengo que setear el PHP a este valor)

**Contexto adicional**

Adjunto report: 
[report_webpay_1598976210.pdf](https://github.com/TransbankDevelopers/transbank-plugin-opencart-webpay/files/5157609/report_webpay_1598976210.pdf)

**Comment by Corobori** [comment]
Al parecer se debe a PHP: 7.3.1, que sé que Usted no soporta pero como mi versión de OpenCart lo exige no tengo otra:  encontré [este parche](https://forum.opencart.com/viewtopic.php?f=202&t=219633) y [este](https://forum.opencart.com/viewtopic.php?f=190&t=216579&start=20#p796020) que me permitieron correr el plugin con PHP 7.3. Creo que no sería una mala idea contemplar eso en una futura versión. 

Si necesitan alguien para probar lo podemos ver.

**Comment by Noxvill** [comment]
@Corobori  Hola, sorry como hiciste para arreglar esto?, estoy intentando implementar webpay con opencart y al momeno de pagar tengo exactamente el mismo error que tu, hice loque aparece en [este parche ](https://forum.opencart.com/viewtopic.php?f=202&t=219633) que dejaste tu y [este otro](https://forum.opencart.com/viewtopic.php?f=190&t=216579&start=20#p796020) que dejaste no logré aplicarlo. Aún cuando hice la configuración del primero no me resolvió el problema, en otros navegadores funciona super bien la integración, pero en el bendito chrome no hay caso, te agradecería enormemente si me pudieras dar una mano, saludos!!.

**Comment by ffiebig** [comment]
Voy a subir un release en un momento con un cambio que debería dejar esto solucionado, pruebalo luego y me cuentas

**Comment by ffiebig** [comment]
@Corobori @Noxvill ya está listo el release https://github.com/TransbankDevelopers/transbank-plugin-opencart-webpay/releases es el ultimo, el 2.2.1

**Comment by Noxvill** [comment]
@ffiebig me funcionó a la primera!!, grande 10 mil gracias!! 👍

**Comment by diegoarmando91** [comment]
@Noxvill hola, una consulta se que este no es el hilo pero en opencart usas journal3 como template o usas el que trae por default? es que tengo un problema al retornar desde webpay (Asumiendo el pago exitoso) al llegar al sitio del comercio me devuelve el error Undefined variable: itemsId in ..\catalog\controller\extension\payment\webpay.php on line 117, por lo visto la función $this->cart->getProducts() no recupera el carro de productos siendo que cuando se regenera la sesión en $this->session->start($session_id) esto se genera correctamente. :(
